### ISSUE TITLE
[BUG] Attachments are not transferred when the note is moved

### ISSUE THREAD

**Issue by marconoris** [dy-sh/obsidian-consistent-attachments-and-links#120]
### Description

In my main vault or in the sandbox, moving the files from one folder to another, does not move the attachments, but creates an alt text with the correct path in the attachment's wikilink.

### Steps to Reproduce

1. Open file in source mode
2. Open command palette 
3. Select "Move file to" and select destination folder

### Expected Behavior

I hope the attachments move with the main file.

### Actual Behavior

Attachments remain in the original folder

### Environment Information

- **Plugin Version**: 3.21.8
- **Obsidian Version**: 1.7.6
- **Operating System**: MacOS 15.1

### Attachments

[Obsidian Sandbox.zip](https://github.com/user-attachments/files/17781390/Obsidian.Sandbox.zip)
[Video](https://github.com/user-attachments/assets/e0208cd5-4681-44a9-bb34-847033c3b33d)

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by whoubeizin** [comment]
I meet the same bug in Windows too, and the environment informations are same with marconoris.

**Comment by jpwegmuller50** [comment]
Same issue for me.

- **Plugin Version**: 3.21.8
- **Obsidian Version**: 1.7.6
- **Operating System**: Windows 11

**Comment by ks00x** [comment]
same here on linux. This used to work until now. Not sure if it is because of Obsidian or plugin update.

**Comment by jmesterh** [comment]
Was going to say "me too" for this bug, however I found that it actually works correctly if the note has the correct relative path for the attachment. Attachments that have no relative path would _not_ move with the note, but after running "Convert all embed paths to relative" (which fixed the links) I am able to move notes around with their attachments.

**Comment by mnaoumov** [comment]
@marconoris in your case, the plugin behaves as expected

![image](https://github.com/user-attachments/assets/5c3b57eb-904b-44fa-a3dc-3a1f6ca2b960)

Based on your setting, the attachments have to be in root vault folder.

So the attachments don't have to be moved.

However if you configure according to what you actually have

![image](https://github.com/user-attachments/assets/2bf21c4a-2529-4da6-ac95-0c2c14520711)

The the plugin has to move the attachments

And this was fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/3.21.11

**Comment by ks00x** [comment]
Thank you! Seems to work now again!!!  One needs to restart Obsidian before the new plugin version is used.
