### ISSUE TITLE
Add notification if some links became invalid after note renaming/moving

### ISSUE THREAD

**Issue by dy-sh** [dy-sh/obsidian-consistent-attachments-and-links#3]

**Comment by u1mp3** [comment]
First of all: thank you for your plugins! Not being a coder myself, I'm grateful you share your work!

I noticed the plugin quite often fails to auto-rename links when renaming notes, causing to loose backlinks. My way of dealing with this is watching the backlinks disappear when renaming a note and meanwhile Obsidian (v.0.11.13) offers to update the internal links, instead of choosing "Do not update" I wait to see if the backlinks reappear again when the plugin is "fixing consistency". Often it says "complete" and I have to let Obsidian update the links for them to appear as backlinks in the renamed note again:
![rename](https://user-images.githubusercontent.com/83334961/116816904-3b020700-ab64-11eb-803c-02ab902fdc2f.gif)
I use the latest version of both the 'Consistent attachments and links'-plugin and the 'Unique attachments'-plugin with all options enabled, having configured Obsidian as indicated in the wikis with all notes and attachments in the root folder, only using 1 subfolder for the templates. Is there anything I can do about this?

**Comment by derwish-pro** [comment]
Hello. I added "Check vault consistent" command to the plugin, and always run it to check that the rename was successful and the links did not break. Not so long ago, I was restructuring my huge vault and did not encounter any problems when renaming and moving notes. I always answer "Do not update" when obsidian suggests updating links. You can try "Check vault consistent" command to detect the conditions when the problem occurs. I can try to figure out the problem if you make a test vault that shows the problem and send the link so I can download it and see what the problem is.

**Comment by mnaoumov** [comment]
This should not be happening anymore. The plugin tries its best not to break any links
